server:
  port: 9001
  tomcat:
#   105 page
#   Свойство определяет предел времени, в течение которого Tomcat должен ждать между принятием TCP-соединения от клиента и фактическим получением HTTP-запроса. Это помогает предотвратить атаки типа «отказ в обслуживании» (DoS), когда соединение установлено, Tomcat резервирует поток для обработки запроса, а запрос никогда не приходит
#   Тот же тайм-аут используется для ограничения времени, затрачиваемого на чтение тела HTTP-запроса, если оно есть
    connection-timeout: 2s
#   Время ожидания повторных запросов пользователя
    keep-alive-timeout: 15s
    threads:
#     Максимальное количество потоков, по умолчанию 200
      max: 50
#     Количество потоков работающих постоянно
      min-spare: 5
